//! Concrete domain types.
//!
//! All entities derive `Serialize`/`Deserialize` so a full profile setup can be
//! exported and imported elsewhere, and so live usage/log data can be surfaced
//! through the API later.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// A tenant in AGOS Proxy.
///
/// A profile owns a set of providers and a set of proxies. Its opaque `id`
/// doubles as the bearer token that callers present against the HTTP API, so it
/// is generated by the CLI and treated like any other secret.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Profile {
    /// Opaque identifier, generated once; also acts as the caller's API token.
    pub id: String,
    /// Human-readable label, e.g. `coder1`.
    pub name: String,
    /// Optional free-text description.
    pub description: Option<String>,
    /// Optional argon2 hash used to gate interactive management of this profile.
    pub password_hash: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    /// Requests-per-minute ceiling for API callers; 0 means unlimited.
    pub rpm_limit: i64,
}

/// What wire format a provider speaks. AGOS Proxy uses this to pick a request
/// and response translator. `OpenAiCompatible` covers most providers; native
/// Anthropic/Google shapes are translated rather than treated as identical.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProviderKind {
    OpenAICompatible,
    Anthropic,
    Google,
    /// OpenAI *Responses* API (`POST {base}/v1/responses`). Some models (e.g.
    /// Zen muse-*) only serve this endpoint; chat requests are translated on
    /// the way out and the reply is reshaped back into chat-completion form.
    OpenAIResponses,
    Custom,
}

/// A configured upstream, belonging to a [`Profile`].
///
/// This is *how* AGOS Proxy reaches a model: the base URL to talk to and the
/// credentials to present. The stored token is encrypted at rest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Provider {
    pub id: i64,
    pub profile_id: String,
    pub name: String,
    pub description: Option<String>,
    pub base_url: String,
    /// Encrypted at rest; never returned by the API in clear text.
    pub auth_token: String,
    pub kind: ProviderKind,
    /// Optional non-standard headers some providers require.
    pub extra_headers: BTreeMap<String, String>,
}

/// A named group of routes a profile exposes, e.g. `Programmer`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Proxy {
    pub id: i64,
    pub profile_id: String,
    pub name: String,
    pub description: Option<String>,
}

/// How an ordered chain of models is picked from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RoutingStrategy {
    /// Strict pipeline order: entry 1, then 2, ... on failure.
    Priority,
    /// Distribute across currently-healthy entries round-robin.
    RoundRobin,
    /// Like round robin, but biased by each entry's weight.
    Weighted,
    /// Cheap-first: entries sorted by blended price (in+out), cheapest tried
    /// first, expensive flagship only on failure or explicit escalation.
    /// This is the economy tier — same output, minimal spend.
    Economy,
}

/// A single addressable target, e.g. `php-developer-3.5-flash`, owned by a
/// [`Proxy`]. The name is what callers send as the OpenAI `model` string
/// (prefixed with the proxy, e.g. `programmer/php-developer-3.5-flash`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Route {
    pub id: i64,
    pub proxy_id: i64,
    pub name: String,
    pub description: Option<String>,
    pub strategy: RoutingStrategy,
    /// Optional identity description. When set, the proxy injects a system
    /// message telling the model to adopt this identity — never revealing its
    /// original model name or developer. When None, the model behaves normally.
    pub identity: Option<String>,
    /// Economy tuning: clamp upstream `max_tokens` (0 = passthrough).
    #[serde(default)]
    pub max_tokens: u32,
    /// Economy tuning: exact-cache TTL in seconds (0 = disabled).
    #[serde(default)]
    pub cache_ttl_secs: i64,
}

/// Automated health state of a route entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ModelStatus {
    /// In normal rotation; used for live traffic.
    Healthy,
    /// Failed or slow recently but still offered (demotes to Unhealthy).
    Degraded,
    /// Skipped from live traffic; probed again in the background.
    Unhealthy,
    /// Switched off manually by the user, regardless of health.
    Disabled,
}

/// One rung of a route's fallback chain: a real model on one configured provider.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RouteEntry {
    pub id: i64,
    pub route_id: i64,
    /// The configured provider used to reach this model.
    pub provider_id: i64,
    /// The model string the underlying provider expects, e.g. `deepseek-v4-flash`.
    pub model_id: String,
    /// Order in the fallback chain; 1 is tried first.
    pub priority: i32,
    /// Relative weight, used only when the route strategy is `Weighted`.
    pub weight: f64,
    pub status: ModelStatus,
    /// Optional capability flags used to skip models that cannot serve a request
    /// (e.g. no tool calling when the request needs it).
    pub capabilities: RouteCapabilities,
    /// Blended price in USD per 1M tokens (input+output average). Used only by
    /// `Economy` strategy to sort cheapest-first. 0.0 = unknown (last).
    #[serde(default)]
    pub price_per_1m: f64,
}

/// Optional feature flags on a route entry, used to avoid routing a request to a
/// model that cannot actually serve it.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RouteCapabilities {
    /// Supports tool / function calling.
    pub tools: bool,
    /// Supports image (vision) input.
    pub vision: bool,
    /// Supports structured JSON output (`response_format`).
    pub json_mode: bool,
    /// Maximum context window in tokens; `None` if unknown.
    pub max_context: Option<u32>,
}

/// One logged request against a route entry: outcome, latency, and token use.
///
/// Written by the server on every completion attempt (streaming or not) and
/// surfaced through `agos-proxy logs` / `agos-proxy stats`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageRecord {
    pub id: i64,
    pub profile_id: String,
    pub route_entry_id: i64,
    pub model_id: String,
    pub streamed: bool,
    pub success: bool,
    pub status_code: Option<i32>,
    pub error_message: Option<String>,
    pub latency_ms: i64,
    pub prompt_tokens: Option<i64>,
    pub completion_tokens: Option<i64>,
    pub created_at: i64,
}

/// Aggregate usage per model over a window: calls, failures, latency, tokens.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageStats {
    pub model_id: String,
    pub calls: i64,
    pub failures: i64,
    pub avg_latency_ms: f64,
    pub prompt_tokens: i64,
    pub completion_tokens: i64,
    /// Estimated cost in USD derived from `RouteEntry::price_per_1m`.
    #[serde(default)]
    pub est_cost_usd: f64,
}
