//! Concrete domain types.
//!
//! All entities derive `Serialize`/`Deserialize` so a full profile setup can be
//! exported and imported elsewhere, and so live usage/log data can be surfaced
//! through the API later.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// A tenant in AGOS Proxy.
///
/// A profile owns a set of providers and a set of proxies. Its opaque `id`
/// doubles as the bearer token that callers present against the HTTP API, so it
/// is generated by the CLI and treated like any other secret.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Profile {
    /// Opaque identifier, generated once; also acts as the caller's API token.
    pub id: String,
    /// Human-readable label, e.g. `coder1`.
    pub name: String,
    /// Optional free-text description.
    pub description: Option<String>,
    /// Optional argon2 hash used to gate interactive management of this profile.
    pub password_hash: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    /// Requests-per-minute ceiling for API callers; 0 means unlimited.
    pub rpm_limit: i64,
    /// Mask used by providers that do not bind one of their own; `None` means
    /// such providers egress directly. A provider-level binding always wins.
    #[serde(default)]
    pub default_masking_server_id: Option<i64>,
}

/// What wire format a provider speaks. AGOS Proxy uses this to pick a request
/// and response translator. `OpenAI` covers most providers; native
/// Anthropic/Google shapes are translated rather than treated as identical.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProviderKind {
    OpenAI,
    Anthropic,
    Google,
    /// OpenAI *Responses* API (`POST {base}/v1/responses`). Some models only
    /// serve this endpoint; chat requests are translated on
    /// the way out and the reply is reshaped back into chat-completion form.
    OpenAIResponses,
    Custom,
}

/// A configured upstream, belonging to a [`Profile`].
///
/// This is *how* AGOS Proxy reaches a model: the base URL to talk to and the
/// credentials to present. The stored token is encrypted at rest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Provider {
    pub id: i64,
    pub profile_id: String,
    pub name: String,
    pub description: Option<String>,
    pub base_url: String,
    /// Encrypted at rest; never returned by the API in clear text.
    pub auth_token: String,
    pub kind: ProviderKind,
    /// Optional non-standard headers some providers require.
    pub extra_headers: BTreeMap<String, String>,
    /// Egress mask this provider's requests leave through. `None` falls back to
    /// the owning profile's default mask, and then to a direct connection.
    #[serde(default)]
    pub masking_server_id: Option<i64>,
    /// The *effective* mask for this provider, denormalized at load time so every
    /// egress path (chat forwarding, health probes, model listing) can reach it
    /// without a second store lookup.
    ///
    /// `Some` when the provider binds a mask itself **or** its profile sets a
    /// default; `None` means the provider egresses directly. Read
    /// [`Provider::masking_server_id`] for the explicit binding alone.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub masking_server: Option<MaskingServer>,
    /// Whether this provider is published to the whole instance. A shared
    /// provider can be referenced from any profile's route chain (the owning
    /// profile's credentials are used, never exposed), while only its owner can
    /// edit or delete it.
    #[serde(default)]
    pub shared: bool,
}

/// An HTTP egress hop ("mask") that upstream requests are relayed through.
///
/// A mask is deliberately dumb and platform-neutral: it receives the absolute
/// upstream URL plus a shared secret in request headers, forwards the body
/// untouched, and streams the reply back. Cloudflare Workers, AWS Lambda,
/// Cloud Run services, plain nginx boxes and commercial proxies can all satisfy
/// that contract, so switching backend is a configuration change rather than a
/// code change.
///
/// Binding a mask to a provider is what makes several upstream keys present
/// distinct network identities, instead of every key egressing from the IP of
/// the host running AGOS.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaskingServer {
    pub id: i64,
    pub profile_id: String,
    /// Human-readable label, e.g. `opencode-key-1`.
    pub name: String,
    /// Free-form backend label for display and presets, e.g. `cf_worker`,
    /// `lambda`, `cloud_run`, `nginx`, `vps`, `commercial`.
    pub kind: String,
    /// Absolute URL of the hop, e.g. `https://edge-1.example.workers.dev`.
    pub endpoint_url: String,
    /// Shared secret presented as `X-forward-mask`. Encrypted at rest like a
    /// provider token, and `skip`ped by serde so it can never be serialized
    /// into an API response or an export.
    #[serde(skip)]
    pub secret: String,
    /// Requests whose body exceeds this size skip the mask instead of failing
    /// on it (0 = no limit). Serverless backends cap request bodies (a Lambda
    /// at 6 MB), and a base64 image blows past that.
    #[serde(default)]
    pub max_body_bytes: i64,
    /// Optional pin: the egress IP this mask is expected to present, checked by
    /// `mask audit`.
    pub expected_egress_ip: Option<String>,
    /// Last egress identity reported by the mask's probe endpoint.
    pub last_verified_ip: Option<String>,
    pub last_verified_asn: Option<String>,
    pub last_verified_country: Option<String>,
    /// Unix millis of the last successful probe.
    pub last_verified_at: Option<i64>,
    /// Whether this mask is published to the whole instance. A shared mask may
    /// carry egress for shared providers used by other profiles; its secret
    /// still never leaves the store.
    #[serde(default)]
    pub shared: bool,
}

/// A named group of routes a profile exposes, e.g. `Programmer`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Proxy {
    pub id: i64,
    pub profile_id: String,
    pub name: String,
    pub description: Option<String>,
}

/// How an ordered chain of models is picked from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RoutingStrategy {
    /// Strict pipeline order: entry 1, then 2, ... on failure.
    Priority,
    /// Distribute across currently-healthy entries round-robin.
    RoundRobin,
    /// Like round robin, but biased by each entry's weight.
    Weighted,
    /// Cheap-first: entries sorted by blended price (in+out), cheapest tried
    /// first, expensive flagship only on failure or explicit escalation.
    /// This is the economy tier — same output, minimal spend.
    Economy,
}

/// A single addressable target, e.g. `php-developer-3.5-flash`, owned by a
/// [`Proxy`]. The name is what callers send as the OpenAI `model` string
/// (prefixed with the proxy, e.g. `programmer/php-developer-3.5-flash`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Route {
    pub id: i64,
    pub proxy_id: i64,
    pub name: String,
    pub description: Option<String>,
    pub strategy: RoutingStrategy,
    /// Optional identity description. When set, the proxy injects a system
    /// message telling the model to adopt this identity — never revealing its
    /// original model name or developer. When None, the model behaves normally.
    pub identity: Option<String>,
    /// Economy tuning: clamp upstream `max_tokens` (0 = passthrough).
    #[serde(default)]
    pub max_tokens: u32,
    /// Economy tuning: exact-cache TTL in seconds (0 = disabled).
    #[serde(default)]
    pub cache_ttl_secs: i64,
}

/// Automated health state of a route entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ModelStatus {
    /// In normal rotation; used for live traffic.
    Healthy,
    /// Failed or slow recently but still offered (demotes to Unhealthy).
    Degraded,
    /// Skipped from live traffic; probed again in the background.
    Unhealthy,
    /// Switched off manually by the user, regardless of health.
    Disabled,
}

/// One rung of a route's fallback chain: a real model on one configured provider.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RouteEntry {
    pub id: i64,
    pub route_id: i64,
    /// The configured provider used to reach this model.
    pub provider_id: i64,
    /// The model string the underlying provider expects, e.g. `my-model-v2`.
    pub model_id: String,
    /// Order in the fallback chain; 1 is tried first.
    pub priority: i32,
    /// Relative weight, used only when the route strategy is `Weighted`.
    pub weight: f64,
    pub status: ModelStatus,
    /// Optional capability flags used to skip models that cannot serve a request
    /// (e.g. no tool calling when the request needs it).
    pub capabilities: RouteCapabilities,
    /// Blended price in USD per 1M tokens (input+output average). Used only by
    /// `Economy` strategy to sort cheapest-first. 0.0 = unknown (last).
    #[serde(default)]
    pub price_per_1m: f64,
    /// Unix-millis instant until which the router skips this entry because the
    /// upstream rate-limited it (0 = not cooling).
    ///
    /// Deliberately orthogonal to [`ModelStatus`]: a background health probe may
    /// flip a rate-limited key back to `Healthy`, but the cooldown still holds,
    /// because a reachable key is not the same thing as a key with quota left.
    #[serde(default)]
    pub cooldown_until: i64,
}

/// Optional feature flags on a route entry, used to avoid routing a request to a
/// model that cannot actually serve it.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RouteCapabilities {
    /// Supports tool / function calling.
    pub tools: bool,
    /// Supports image (vision) input.
    pub vision: bool,
    /// Supports structured JSON output (`response_format`).
    pub json_mode: bool,
    /// Maximum context window in tokens; `None` if unknown.
    pub max_context: Option<u32>,
}

/// Per-key aggregate: how a profile's traffic spread across the upstream
/// accounts behind its routes.
///
/// The operational view for a profile that spreads several keys of one upstream
/// across several egress masks: it shows, per key, how much work each one
/// carried and how often it was throttled, which is how you tell whether the
/// keys are actually being used in parallel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyStats {
    pub provider_id: i64,
    pub provider_name: String,
    /// Egress mask this key leaves through, when one is bound.
    pub mask_name: Option<String>,
    pub calls: i64,
    pub failures: i64,
    /// Responses that came back `429`, i.e. this key hit its quota.
    pub rate_limited: i64,
    pub avg_latency_ms: f64,
}

/// One logged request against a route entry: outcome, latency, and token use.
///
/// Written by the server on every completion attempt (streaming or not) and
/// surfaced through `agos-proxy logs` / `agos-proxy stats`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageRecord {
    pub id: i64,
    pub profile_id: String,
    pub route_entry_id: i64,
    pub model_id: String,
    pub streamed: bool,
    pub success: bool,
    pub status_code: Option<i32>,
    pub error_message: Option<String>,
    pub latency_ms: i64,
    pub prompt_tokens: Option<i64>,
    pub completion_tokens: Option<i64>,
    pub created_at: i64,
}

/// Aggregate usage per model over a window: calls, failures, latency, tokens.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageStats {
    pub model_id: String,
    pub calls: i64,
    pub failures: i64,
    pub avg_latency_ms: f64,
    pub prompt_tokens: i64,
    pub completion_tokens: i64,
    /// Estimated cost in USD derived from `RouteEntry::price_per_1m`.
    #[serde(default)]
    pub est_cost_usd: f64,
}
